# Generated by Django 5.2.4 on 2025-09-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceFluctuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_info", models.TextField()),
                ("reason", models.TextField()),
                ("links", models.JSONField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StockInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("market_type", models.CharField(max_length=255)),
                ("industry_tag", models.CharField(max_length=255)),
                ("company_profile", models.TextField()),
            ],
        ),
    ]
