# Generated by Django 5.2.4 on 2025-09-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("interests", models.JSONField(default={})),
            ],
        ),
    ]
