# Generated by Django 5.2.4 on 2025-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                editable=False, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
