# Generated by Django 5.2.4 on 2025-10-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_interests_user_profile_id_interests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interests",
            options={"ordering": ["-create_at"]},
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_id",
        ),
    ]
