# Generated by Django 5.2.4 on 2025-10-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_interests_options_remove_user_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
