# Generated by Django 5.2.4 on 2025-10-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_refresh_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interests", models.JSONField()),
                ("strategy", models.JSONField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user"),
                ),
            ],
            options={
                "ordering": ["-create_at"],
            },
        ),
        migrations.DeleteModel(
            name="Interests",
        ),
    ]
