# Generated by Django 5.2.4 on 2025-10-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_style_delete_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
