# Generated by Django 5.2.4 on 2025-10-25 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_date', models.DateField(help_text='KST 기준 추천 일자')),
                ('risk_profile', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(default='llm', max_length=16)),
                ('model_id', models.CharField(blank=True, max_length=64, null=True)),
                ('as_of_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('market', 'Market'), ('industry', 'Industry'), ('global', 'Global')], default='global', max_length=16)),
                ('industry_tag', models.CharField(blank=True, max_length=64, null=True)),
                ('audience', models.CharField(choices=[('general', 'General'), ('personalized', 'Personalized')], default='general', max_length=16)),
                ('regime', models.CharField(blank=True, choices=[('market_risk_on', 'Risk On'), ('market_neutral', 'Neutral'), ('market_risk_off', 'Risk Off')], max_length=32, null=True)),
                ('inputs_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendation_batches',
                'indexes': [models.Index(fields=['market_date', 'level', 'audience'], name='recommendat_market__c923d3_idx'), models.Index(fields=['market_date', 'risk_profile'], name='recommendat_market__1a6280_idx')],
                'constraints': [models.UniqueConstraint(fields=('market_date', 'risk_profile', 'level', 'industry_tag', 'audience'), name='uq_batch_day_profile_level_industry_audience')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('ticker', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('market', models.CharField(default='KOSPI', max_length=10)),
                ('news', models.JSONField(default=list)),
                ('reason', models.JSONField(default=list)),
                ('expected_direction', models.CharField(choices=[('up', 'Up'), ('neutral', 'Neutral'), ('down', 'Down')], default='neutral', max_length=10)),
                ('conviction', models.FloatField(default=0.5)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('score_breakdown', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.recommendationbatch')),
            ],
            options={
                'db_table': 'recommendation_items',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['batch', 'rank'], name='recommendat_batch_i_017632_idx'), models.Index(fields=['ticker'], name='recommendat_ticker_c7c4c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'rank'), name='uq_item_batch_rank'), models.UniqueConstraint(fields=('batch', 'ticker'), name='uq_item_batch_ticker'), models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='ck_item_rank_ge_1'), models.CheckConstraint(condition=models.Q(('conviction__gte', 0.0), ('conviction__lte', 1.0)), name='ck_item_conviction_0_1')],
            },
        ),
    ]
