# Generated by Django 5.2.4 on 2025-10-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=128)),
                ('interests', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('exchange', models.CharField(max_length=16)),
                ('sector', models.CharField(blank=True, max_length=64, null=True)),
                ('industry', models.CharField(blank=True, max_length=64, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='MacroIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=32)),
                ('ts', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'macro_indices',
                'indexes': [models.Index(fields=['series', 'ts'], name='macro_indic_series_75f722_idx')],
                'unique_together': {('series', 'ts')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_date', models.DateField(help_text='KST 기준 추천 일자')),
                ('risk_profile', models.CharField(max_length=32)),
                ('source', models.CharField(default='mock', max_length=16)),
                ('model_id', models.CharField(blank=True, max_length=64, null=True)),
                ('as_of_utc', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendation_batches',
                'unique_together': {('market_date', 'risk_profile')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('ticker', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('news_titles', models.JSONField(default=list)),
                ('news_urls', models.JSONField(default=list)),
                ('reason', models.JSONField(default=list)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.recommendationbatch')),
            ],
            options={
                'db_table': 'recommendation_items',
                'indexes': [models.Index(fields=['batch', 'rank'], name='recommendat_batch_i_017632_idx'), models.Index(fields=['ticker'], name='recommendat_ticker_c7c4c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('bps', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('pbr', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
            options={
                'db_table': 'prices_financials',
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
