# Generated by Django 5.2.4 on 2025-10-19 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_date', models.DateField(help_text='KST 기준 추천 일자')),
                ('risk_profile', models.CharField(max_length=32)),
                ('source', models.CharField(default='db', max_length=16)),
                ('model_id', models.CharField(blank=True, max_length=64, null=True)),
                ('as_of_utc', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendation_batches',
                'unique_together': {('market_date', 'risk_profile')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('ticker', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('news_titles', models.JSONField(default=list)),
                ('news_urls', models.JSONField(default=list)),
                ('reason', models.JSONField(default=list)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.recommendationbatch')),
            ],
            options={
                'db_table': 'recommendation_items',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['batch', 'rank'], name='recommendat_batch_i_017632_idx'), models.Index(fields=['ticker'], name='recommendat_ticker_c7c4c5_idx')],
            },
        ),
    ]
