# Generated by Django 5.2.4 on 2025-10-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationitem',
            name='conviction',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='expected_direction',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='recommendationitem',
            name='market',
            field=models.CharField(default='KOSPI', max_length=10),
        ),
    ]
